project_id = "dtknywnttoslxthlqwsz"

[functions.send-email]
verify_jwt = false

[functions.s3-upload]
verify_jwt = false

[functions.s3-signed-url]
verify_jwt = false

[functions.create-client]
verify_jwt = false

[functions.hash-password]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.manage-admin-user]
verify_jwt = false

[functions.manage-work]
verify_jwt = false

[functions.upload-asset]
verify_jwt = false

[functions.verify-share-password]
verify_jwt = false

[functions.face-detection]
verify_jwt = false

[functions.get-share-gallery]
verify_jwt = false

[functions.send-questionnaire]
verify_jwt = false

[functions.questionnaire]
verify_jwt = false

[functions.storage-cleanup]
verify_jwt = false
